version: "3.3"
networks:
  dev:
    name: dev
services:
  test:
    image: docker
    restart: always
    volumes:
      - .:/ooo
    working_dir: /ooo
    networks:
      - dev
    command:
      - /bin/sh
      - -c
      - |
        sleep 1000000
